// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMUxWc_1z_4Da-Q_rArn5HiNZ312D-UiU',
    appId: '1:485430213995:android:2599509826f00c8fd5a02e',
    messagingSenderId: '485430213995',
    projectId: 'naem-o',
    storageBucket: 'naem-o.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvD7ExuLVkCdnLsDbG0Nk76nTTmG64XPE',
    appId: '1:485430213995:ios:c8da87c241d9ebefd5a02e',
    messagingSenderId: '485430213995',
    projectId: 'naem-o',
    storageBucket: 'naem-o.firebasestorage.app',
    androidClientId:
        '485430213995-ct7n7h0t24agcrt6su8kvq9gkk8du8lo.apps.googleusercontent.com',
    iosClientId:
        '485430213995-ccopd7sedfsss28reruuvk15cnl3eu53.apps.googleusercontent.com',
    iosBundleId: 'com.bolliverse.todo.todoProject',
  );
}
